version: '3.7'

services:
    php:
        build:
            dockerfile: etc/artifact/Dockerfile
            context: .
            target: sylius_php
            cache_from:
                - quay.io/sylius/php:latest
                - quay.io/sylius/nodejs:latest
                - quay.io/sylius/nginx:latest
        image: quay.io/sylius/php:latest
        depends_on:
          - mysql
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - APP_SECRET=EDITME
            - DATABASE_URL=mysql://sylius:nopassword@mysql/sylius
            - MAILER_URL=smtp://mailhog:1025
            - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
        volumes:
            - .:/srv/sylius:rw,cached
            - ./public:/srv/sylius/public:rw,delegated
            - public-media:/srv/sylius/public/media:rw
        
    mysql:
        image: percona:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
            - MYSQL_DATABASE=sylius
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
        volumes:
            - mysql-data:/var/lib/mysql:rw
          
    nodejs:
        build:
            dockerfile: etc/artifact/Dockerfile
            context: .
            target: sylius_nodejs
            cache_from:
                - quay.io/sylius/php:latest
                - quay.io/sylius/nodejs:latest
                - quay.io/sylius/nginx:latest
        image: quay.io/sylius/nodejs:latest
        depends_on:
            - php
        environment:
            - GULP_ENV=dev
            - PHP_HOST=php
            - PHP_PORT=9000
        volumes:
            - .:/srv/sylius:rw,cached
            - ./public:/srv/sylius/public:rw,delegated
        
    nginx:
        build:
            dockerfile: etc/artifact/Dockerfile
            context: .
            target: sylius_nginx
            cache_from:
                - quay.io/sylius/php:latest
                - quay.io/sylius/nodejs:latest
                - quay.io/sylius/nginx:latest
        image: quay.io/sylius/nginx:latest
        depends_on:
            - php
            - nodejs
        volumes:
            - ./public:/srv/sylius/public:ro
            - public-media:/srv/sylius/public/media:ro,nocopy
    start_dependencies:
        image: dadarek/wait-for-dependencies
        depends_on:
            - mysql
        command: mysql:3306
volumes:
    public-media:
    mysql-data:
